version: '3.8'

networks:
  hospital:
volumes:
  hospital-db:
  storage-member:
  log-auth:
  log-locations:
  log-members:

services:
  db:
    image: postgres:alpine
    container_name: hospital-db
    networks:
      - hospital
    ports:
      - 5432:5432
    environment:
      - TZ="Asia/Yangon"
      - POSTGRES_DB=hospital_db
      - POSTGRES_USER=hospitalusr
      - POSTGRES_PASSWORD=hospitalpwd
    volumes:
      - hospital-db:/var/lib/postgresql/data

  auth:
    build: ./hospital-auth
    container_name: hospital-auth
    networks:
      - hospital
    ports:
      - 8080:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - db
    volumes:
      - log-auth:/var/log/application

  locations:
    build: ./hospital-locations
    container_name: hospital-locations
    networks:
      - hospital
    ports:
      - 8081:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-locations:/var/log/application

  members:
    build: ./hospital-members
    container_name: hospital-members
    networks:
      - hospital
    ports:
      - 8082:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-members:/var/log/application
