version: '3.8'

networks:
  hospital:

volumes:
  hospital-db:
  rabbit:
  storage-members:
  log-auth:
  log-locations:
  log-members:
  log-appointments:
  log-reviews:

services:
  db:
    image: postgres:alpine
    container_name: hospital-db
    networks:
      - hospital
    ports:
      - 5432:5432
    environment:
      - TZ="Asia/Yangon"
      - POSTGRES_DB=hospital_db
      - POSTGRES_USER=hospitalusr
      - POSTGRES_PASSWORD=hospitalpwd
    volumes:
      - hospital-db:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: hospital-mq
    networks:
      - hospital
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=mqclient'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq
  auth:
    build: ./hospital-auth
    container_name: hospital-auth
    networks:
      - hospital
    ports:
      - 8080:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - log-auth:/var/log/application

  locations:
    build: ./hospital-locations
    container_name: hospital-locations
    networks:
      - hospital
    ports:
      - 8081:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-locations:/var/log/application

  members:
    build: ./hospital-members
    container_name: hospital-members
    networks:
      - hospital
    ports:
      - 8082:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-members:/var/log/application
      - storage-members:/var/lib/storage	  

  appointments:
    build: ./hospital-appointments
    container_name: hospital-appointments
    networks:
      - hospital
    ports:
      - 8083:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-appointments:/var/log/application

  reviews:
    build: ./hospital-review
    container_name: hospital-reviews
    networks:
      - hospital
    ports:
      - 8084:8080
    environment:
      - TZ="Asia/Yangon"
    depends_on:
      - auth
    volumes:
      - log-reviews:/var/log/application
